version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: movieqa-bot
    container_name: movieqa-bot
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
      - ./transcript:/app/transcript
      - ./vectorstore:/app/vectorstore
      - chroma_data:/app/chroma_db
    # Default: run CLI mode (app.py)
    command: >
      sh -c "python app.py ${VIDEO_ID:-''} \"${QUESTION:-''}\""

  streamlit:
    image: movieqa-bot
    container_name: movieqa-ui
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./transcript:/app/transcript
      - ./vectorstore:/app/vectorstore
      - chroma_data:/app/chroma_db
    command: >
      sh -c "streamlit run /app/ui_streamlit.py --server.port=8501 --server.address=0.0.0.0"

volumes:
  chroma_data:
    driver: local