version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: movieqa-bot
    container_name: movieqa-bot
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app                           # Mount entire codebase
      - ./transcript:/app/transcript     # Optional: retain transcripts
      - ./vectorstore:/app/vectorstore   # Optional: retain vectors
      - chroma_data:/app/chroma_db       # Persistent Chroma DB
    command: >
      sh -c "python app.py $VIDEO_ID \"$QUESTION\""

volumes:
  chroma_data:
    driver: local
